# TerminalGuard Configuration File

# Detection settings
detection:
  enabled: true
  case_sensitive: false

# Secret detection patterns
patterns:
  aws_access_key:
    regex: 'AKIA[0-9A-Z]{16}'
    description: 'AWS Access Key ID'
    severity: 'high'
  
  aws_secret_key:
    regex: '[0-9a-zA-Z/+]{40}'
    description: 'AWS Secret Access Key'
    severity: 'high'
  
  github_token:
    regex: 'ghp_[0-9a-zA-Z]{36}'
    description: 'GitHub Personal Access Token'
    severity: 'high'
  
  generic_api_key:
    regex: '(?i)(api[_-]?key|apikey)[\s]*[=:]+[\s]*["'']?([0-9a-zA-Z\-_]{20,})["'']?'
    description: 'Generic API Key'
    severity: 'medium'
  
  password_in_url:
    regex: ':([^\s:@]{3,})@'
    description: 'Password in URL'
    severity: 'high'
  
  password_with_flag:
    regex: '-u\s+\w+:(\S+)'
    description: 'Password with -u flag'
    severity: 'high'
  
  password_assignment:
    regex: '(?i)(password|passwd|pwd)[\s]*[=:]+[\s]*["'']?([^\s"'']{3,})["'']?'
    description: 'Password assignment'
    severity: 'medium'
  
  private_key:
    regex: '-----BEGIN (?:RSA |DSA )?PRIVATE KEY-----'
    description: 'Private SSH/SSL Key'
    severity: 'critical'
  
  jwt_token:
    regex: 'eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'
    description: 'JWT Token'
    severity: 'high'
  
  slack_token:
    regex: 'xox[baprs]-([0-9a-zA-Z]{10,48})'
    description: 'Slack Token'
    severity: 'high'
  
  env_var_secret:
    regex: '(?i)export\s+[A-Z_]*(KEY|TOKEN|SECRET|PASSWORD)[A-Z_]*=\S+'
    description: 'Environment variable with secret'
    severity: 'medium'
  
  token_in_url:
    regex: 'https?://ghp_[0-9a-zA-Z]{36}@'
    description: 'Token embedded in URL'
    severity: 'high'

# Whitelist - commands that bypass secret detection
whitelist:
  commands:
    - 'echo'
    - 'cat config.yaml'
    - 'type config.yaml'
  
  patterns:
    - '^git config'
    - '^history'

# Audit logging settings
audit:
  enabled: true
  log_file: 'audit.log'
  max_size_mb: 10
