# TerminalGuard Configuration File
# Based on patterns from Gitleaks, TruffleHog, and Secrets-Patterns-DB

detection:
  enabled: true
  case_sensitive: false

patterns:
  # AI & LLM Services 
  openai_api_key:
    regex: "sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}"
    description: "OpenAI API Key"
    severity: "critical"

  openai_organization_key:
    regex: "sk-[a-zA-Z0-9-]{48}"
    description: "OpenAI Organization Key"
    severity: "high"

  anthropic_api_key:
    regex: "sk-ant-api03-[a-zA-Z0-9\\-_]{95,}"
    description: "Anthropic (Claude) API Key"
    severity: "critical"

  cohere_api_key:
    regex: "[a-zA-Z0-9]{40}"
    description: "Cohere API Key"
    severity: "high"

  huggingface_token:
    regex: "hf_[a-zA-Z0-9]{32,}"
    description: "Hugging Face Access Token"
    severity: "high"

  mistral_ai_key:
    regex: "[a-zA-Z0-9]{32}"
    description: "Mistral AI API Key"
    severity: "high"

  deepseek_api_key:
    regex: "sk-[a-zA-Z0-9]{48}"
    description: "DeepSeek API Key"
    severity: "high"

  wandb_api_key:
    regex: "[a-f0-9]{40}"
    description: "Weights & Biases API Key"
    severity: "medium"

  replicate_api_token:
    regex: "r8_[a-zA-Z0-9]{40}"
    description: "Replicate API Token"
    severity: "high"

  # Cloud Provider Keys
  aws_access_key:
    regex: "AKIA[0-9A-Z]{16}"
    description: "AWS Access Key ID"
    severity: "high"
    
  aws_secret_key:
    regex: "(?i)aws(.{0,20})?['\"]?[0-9a-zA-Z/+]{40}['\"]?"
    description: "AWS Secret Access Key"
    severity: "high"
    
  aws_account_id:
    regex: "(?i)aws(.{0,20})?['\"]?[0-9]{12}['\"]?"
    description: "AWS Account ID"
    severity: "medium"
    
  azure_subscription_key:
    regex: "[0-9a-f]{32}"
    description: "Azure Subscription Key"
    severity: "high"
    
  azure_storage_key:
    regex: "AccountKey=[0-9a-zA-Z+/=]{88}"
    description: "Azure Storage Account Key"
    severity: "high"
    
  google_api_key:
    regex: "AIza[0-9A-Za-z\\-_]{35}"
    description: "Google API Key"
    severity: "high"
    
  google_cloud_key:
    regex: "(?i)(google|gcp|youtube|yt)(.{0,20})?['\"]?[0-9a-zA-Z\\-_]{24}['\"]?"
    description: "Google Cloud Platform API Key"
    severity: "high"
  
  digitalocean_token:
    regex: "dop_v1_[a-f0-9]{64}"
    description: "DigitalOcean Personal Access Token"
    severity: "high"

  digitalocean_spaces_key:
    regex: "DO[0-9A-Z]{18}"
    description: "DigitalOcean Spaces Access Key"
    severity: "high"

  linode_personal_token:
    regex: "[a-f0-9]{64}"
    description: "Linode Personal Access Token"
    severity: "high"

  vultr_api_key:
    regex: "[A-Z0-9]{36}"
    description: "Vultr API Key"
    severity: "medium"

  # Additional VCS Tokens
  bitbucket_client_id:
    regex: "[a-zA-Z0-9]{32}"
    description: "Bitbucket Client ID"
    severity: "medium"

  bitbucket_client_secret:
    regex: "[a-zA-Z0-9]{32}"
    description: "Bitbucket Client Secret"
    severity: "high"

  azure_devops_pat:
    regex: "[a-z0-9]{52}"
    description: "Azure DevOps Personal Access Token"
    severity: "high"

  # Maps & Location Services
  mapbox_api_key:
    regex: "pk\\.[a-zA-Z0-9]{60,}"
    description: "Mapbox API Key"
    severity: "medium"

  mapbox_secret_token:
    regex: "sk\\.[a-zA-Z0-9]{60,}"
    description: "Mapbox Secret Token"
    severity: "high"

  google_maps_api_key:
    regex: "AIza[0-9A-Za-z\\-_]{35}"
    description: "Google Maps API Key"
    severity: "high"

  openweather_api_key:
    regex: "[a-f0-9]{32}"
    description: "OpenWeather API Key"
    severity: "low"

  # Security & Monitoring Tools
  aikido_api_token:
    regex: "aikido_[a-zA-Z0-9_-]{32,}"
    description: "Aikido Security API Token"
    severity: "high"

  temporal_cloud_api_key:
    regex: "tcld_[a-zA-Z0-9_-]{32,}"
    description: "Temporal Cloud API Key"
    severity: "high"

  guardsquare_token:
    regex: "[a-zA-Z0-9]{32}"
    description: "GuardSquare API Token"
    severity: "medium"

  # GitHub & GitLab
  github_token:
    regex: "ghp_[0-9a-zA-Z]{36}"
    description: "GitHub Personal Access Token"
    severity: "high"
    
  github_oauth:
    regex: "gho_[0-9a-zA-Z]{36}"
    description: "GitHub OAuth Access Token"
    severity: "high"
    
  github_app_token:
    regex: "(ghu|ghs)_[0-9a-zA-Z]{36}"
    description: "GitHub App Token"
    severity: "high"
    
  github_refresh_token:
    regex: "ghr_[0-9a-zA-Z]{76}"
    description: "GitHub Refresh Token"
    severity: "high"
    
  gitlab_pat:
    regex: "glpat-[0-9a-zA-Z\\-_]{20}"
    description: "GitLab Personal Access Token"
    severity: "high"
    
  gitlab_runner_token:
    regex: "glrt-[0-9a-zA-Z\\-_]{20}"
    description: "GitLab Runner Token"
    severity: "high"
    
  # Payment & Commerce
  stripe_api_key:
    regex: "(?i)(sk|pk)_(live|test)_[0-9a-zA-Z]{24,99}"
    description: "Stripe API Key"
    severity: "critical"
    
  stripe_webhook_secret:
    regex: "whsec_[0-9a-zA-Z]{32}"
    description: "Stripe Webhook Secret"
    severity: "high"
    
  paypal_token:
    regex: "access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}"
    description: "PayPal Access Token"
    severity: "high"
    
  square_token:
    regex: "sq0atp-[0-9A-Za-z\\-_]{22}"
    description: "Square Access Token"
    severity: "high"
  
  shopify_webhook_secret:
    regex: "[a-f0-9]{32}"
    description: "Shopify Webhook Secret"
    severity: "high"

  tencent_wechat_pay_token:
    regex: "[a-zA-Z0-9]{32}"
    description: "Tencent WeChat Pay Token"
    severity: "high"
      
  # Communication & Social
  slack_token:
    regex: "xox[baprs]-[0-9a-zA-Z]{10,48}"
    description: "Slack Token"
    severity: "high"
    
  slack_webhook:
    regex: "https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"
    description: "Slack Webhook URL"
    severity: "high"
    
  discord_webhook:
    regex: "https://discord(app)?.com/api/webhooks/[0-9]{18}/[a-zA-Z0-9_-]{68}"
    description: "Discord Webhook"
    severity: "medium"
    
  discord_bot_token:
    regex: "[MN][A-Za-z\\d]{23}\\.[\\w-]{6}\\.[\\w-]{27}"
    description: "Discord Bot Token"
    severity: "high"
    
  telegram_bot_token:
    regex: "[0-9]{8,10}:[0-9A-Za-z_-]{35}"
    description: "Telegram Bot Token"
    severity: "high"
    
  twilio_api_key:
    regex: "SK[0-9a-fA-F]{32}"
    description: "Twilio API Key"
    severity: "high"
    
  twilio_account_sid:
    regex: "AC[0-9a-fA-F]{32}"
    description: "Twilio Account SID"
    severity: "medium"

  zenhub_personal_token:
    regex: "[a-f0-9]{40}"
    description: "ZenHub Personal API Key"
    severity: "medium"

  hcaptcha_secret:
    regex: "0x[a-fA-F0-9]{40}"
    description: "hCaptcha Site Verify Secret"
    severity: "high"
    
  # Email Services
  sendgrid_api_key:
    regex: 'SG\.[a-zA-Z0-9_-]{8,}\.[a-zA-Z0-9_-]{8,}'
    description: "SendGrid API Key"
    severity: "high"
    
  mailgun_api_key:
    regex: "key-[0-9a-zA-Z]{32}"
    description: "Mailgun API Key"
    severity: "high"
    
  mailchimp_api_key:
    regex: "[0-9a-f]{32}-us[0-9]{1,2}"
    description: "Mailchimp API Key"
    severity: "high"
    
  # Databases
  airtable_api_key:
    regex: "pat[a-zA-Z0-9]{14}\\.[a-f0-9]{64}"
    description: "Airtable API Key"
    severity: "high"

  salesforce_access_token:
    regex: "00D[a-zA-Z0-9]{15}![a-zA-Z0-9\\.]{100,}"
    description: "Salesforce Access Token"
    severity: "critical"

  mongodb_uri:
    regex: "mongodb(\\+srv)?://[^\\s:]+:[^\\s@]+@[^\\s/]+/[^\\s?]+(\\?[^\\s]+)?"
    description: "MongoDB Connection URI"
    severity: "critical"
    
  postgres_uri:
    regex: "postgres(ql)?://[^\\s:]+:[^\\s@]+@[^\\s/]+/[^\\s]+"
    description: "PostgreSQL Connection URI"
    severity: "critical"
    
  mysql_uri:
    regex: "mysql://[^\\s:]+:[^\\s@]+@[^\\s/]+/[^\\s]+"
    description: "MySQL Connection URI"
    severity: "critical"
    
  redis_uri:
    regex: "redis://[^\\s:]*:[^\\s@]+@[^\\s/]+/[0-9]+"
    description: "Redis Connection URI"
    severity: "high"

  kubernetes_token:
    regex: "eyJhbGciOi[A-Za-z0-9_\\-\\.=]+"
    description: "Kubernetes Service Account Token"
    severity: "critical"

  docker_hub_token:
    regex: "dckr_pat_[a-zA-Z0-9_-]{36}"
    description: "Docker Hub Personal Access Token"
    severity: "high"
    
  # Authentication & Tokens
  jwt_token:
    regex: "ey[IJA][A-Za-z0-9_-]{10,}\\.ey[IJA][A-Za-z0-9_-]{10,}\\.[A-Za-z0-9._-]{10,}"
    description: "JWT Token (All variants including eyI, eyJ, eyA)"
    severity: "medium"
    
  bearer_token:
    regex: "(?i)bearer\\s+[a-zA-Z0-9_\\-\\.=]{20,}"
    description: "Bearer Token"
    severity: "medium"
    
  oauth_token:
    regex: "(?i)oauth[_-]?token[\\s]*[=:]+[\\s]*[\"']?([0-9a-zA-Z\\-_]+)[\"']?"
    description: "OAuth Token"
    severity: "high"
    
  # API Keys & Secrets
  generic_api_key:
    regex: '(?i)(API_KEY|api_key)[\s=:''"]*([0-9a-zA-Z_\-]{20,})'
    description: 'Generic API Key'
    severity: 'medium'

  # Separation for demo/test API keys (will be ignored)
  demo_api_key:
    regex: '(?i)(API_KEY|api_key)[\s=:''"]*(TEST|DUMMY|EXAMPLE)[0-9a-zA-Z_\-]*'
    description: 'Demo/Test API Key'
    severity: 'ignore'

  generic_secret:
    regex: "(?i)(secret|app_secret)[\\s]*[=:]+[\\s]*[\"']?([0-9a-zA-Z\\-_]{20,})[\"']?"
    description: "Generic Secret"
    severity: "medium"
    
  access_token:
    regex: "(?i)access[_-]?token[\\s]*[=:]+[\\s]*[\"']?([0-9a-zA-Z\\-_]{20,})[\"']?"
    description: "Generic Access Token"
    severity: "medium"

  # Private Keys & Certificates
  rsa_private_key:
    regex: "-----BEGIN RSA PRIVATE KEY-----"
    description: "RSA Private Key"
    severity: "critical"
    
  dsa_private_key:
    regex: "-----BEGIN DSA PRIVATE KEY-----"
    description: "DSA Private Key"
    severity: "critical"
    
  ec_private_key:
    regex: "-----BEGIN EC PRIVATE KEY-----"
    description: "EC Private Key"
    severity: "critical"
    
  openssh_private_key:
    regex: "-----BEGIN OPENSSH PRIVATE KEY-----"
    description: "OpenSSH Private Key"
    severity: "critical"
    
  pgp_private_key:
    regex: "-----BEGIN PGP PRIVATE KEY BLOCK-----"
    description: "PGP Private Key"
    severity: "critical"
    
  ssl_certificate:
    regex: "-----BEGIN (RSA|DSA|EC)? ?CERTIFICATE-----"
    description: "SSL Certificate"
    severity: "low"
    
  # Container & CI/CD
  docker_auth:
    regex: "\\{\\s*\"auths\"\\s*:\\s*\\{.*\"auth\"\\s*:\\s*\"[A-Za-z0-9+/=]{20,}\""
    description: "Docker Auth Configuration"
    severity: "high"
    
  npm_token:
    regex: "npm_[A-Za-z0-9]{36}"
    description: "NPM Access Token"
    severity: "high"
    
  pypi_token:
    regex: "pypi-AgEIcHlwaS5vcmc[A-Za-z0-9\\-_]{50,}"
    description: "PyPI API Token"
    severity: "high"
    
  heroku_api_key:
    regex: "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
    description: "Heroku API Key"
    severity: "high"
    
  travis_token:
    regex: "(?i)travis[_-]?token[\\s]*[=:]+[\\s]*[\"']?([0-9a-zA-Z\\-_]{20,})[\"']?"
    description: "Travis CI Token"
    severity: "medium"
    
  circleci_token:
    regex: "(?i)circle[_-]?token[\\s]*[=:]+[\\s]*[\"']?([0-9a-zA-Z]{40})[\"']?"
    description: "CircleCI Token"
    severity: "high"
  
  kong_admin_token:
    regex: "[a-zA-Z0-9_-]{32,}"
    description: "Kong Admin Token"
    severity: "critical"

  apigee_token:
    regex: "[a-zA-Z0-9]{32}"
    description: "Apigee API Token"
    severity: "high"
    
  # Framework & Application Specific
  django_secret_key:
    regex: "(?i)django[_-]?secret[_-]?key[\\s]*[=:]+[\\s]*[\"']?([0-9a-zA-Z@#$%^&*()\\-_=+]{40,})[\"']?"
    description: "Django Secret Key"
    severity: "high"
    
  flask_secret_key:
    regex: "(?i)flask[_-]?secret[_-]?key[\\s]*[=:]+[\\s]*[\"']?([0-9a-zA-Z@#$%^&*()\\-_=+]{20,})[\"']?"
    description: "Flask Secret Key"
    severity: "high"
    
  rails_secret:
    regex: "(?i)secret_key_base[\\s]*[=:]+[\\s]*[\"']?([0-9a-f]{128})[\"']?"
    description: "Rails Secret Key Base"
    severity: "high"
    
  # Password Patterns
  password_in_url:
    regex: "://[^\\s:]+:([^\\s@]+)@[^\\s/]+"
    description: "Password in URL"
    severity: "high"
    
  password_with_flag:
    regex: "-[pP]\\s+\\S+"
    description: "Password with -p flag"
    severity: "high"
    
  password_assignment:
    regex: "(?i)(password|passwd|pwd)[\\s]*[=:]+[\\s]*[\"']?([^\\s\"']{3,})[\"']?"
    description: "Password assignment"
    severity: "medium"
    
  db_password:
    regex: "(?i)db[_-]?password[\\s]*[=:]+[\\s]*[\"']?([^\\s\"']{3,})[\"']?"
    description: "Database Password"
    severity: "high"
    
  # Environment Variables
  env_secret:
    regex: "(?i)(secret|token|key|password)=[^\\s]+"
    description: "Environment Variable Secret"
    severity: "low"
    
  # Additional Services
  datadog_api_key:
    regex: "[0-9a-f]{32}"
    description: "Datadog API Key"
    severity: "medium"
    
  new_relic_key:
    regex: "[0-9a-f]{40}"
    description: "New Relic License Key"
    severity: "medium"
    
  sentry_dsn:
    regex: "https://[0-9a-f]{32}@[^\\s/]+/[0-9]+"
    description: "Sentry DSN"
    severity: "medium"
    
  cloudflare_token:
    regex: "[A-Za-z0-9_-]{40}"
    description: "Cloudflare API Token"
    severity: "high"
    
  facebook_access_token:
    regex: "EAACEdEose0cBA[0-9A-Za-z]+"
    description: "Facebook Access Token"
    severity: "high"
    
  twitter_bearer_token:
    regex: "AAAAAAAAAAAAAAAAAAAAAA[A-Za-z0-9%]{60,}"
    description: "Twitter Bearer Token"
    severity: "high"
    
  shopify_token:
    regex: "shpat_[0-9a-fA-F]{32}"
    description: "Shopify Access Token"
    severity: "high"
    
  # Encryption Keys
  encryption_key:
    regex: "(?i)encryption[_-]?key[\\s]*[=:]+[\\s]*[\"']?([0-9a-fA-F]{32,})[\"']?"
    description: "Encryption Key"
    severity: "critical"
    
  aes_key:
    regex: "(?i)aes[_-]?key[\\s]*[=:]+[\\s]*[\"']?([0-9a-fA-F]{32,})[\"']?"
    description: "AES Encryption Key"
    severity: "critical"

# Whitelist Configuration
whitelist:
  commands:
    - "git log"
    - "git status"
    - "docker ps"
    - "ls -la"
    - "echo"
    - 'cat config.yaml'
    - 'type config.yaml'
    - 'export API_KEY=devkey_*'
    - 'export API_KEY=TEST*'
    - 'echo API_KEY=devkey_*'
    - 'echo API_KEY=TEST*'
    - 'echo password=examplepassword'
    - 'echo ENV_SECRET=dummysecretvalue'

  patterns:
    - "example\\.com"
    - "localhost"
    - "127\\.0\\.0\\.1"
    - "test[_-]?password"
    - "dummy[_-]?key"
    - "placeholder"
    - "dummy"
    - "XXXXXXXX"
    - "\\*\\*\\*\\*\\*"
    - '^git config'
    - '^history'
    - 'API_KEY=devkey_*'
    - 'API_KEY=TEST*'
    - 'password=examplepassword'
    - 'ENV_SECRET=dummysecretvalue'


# Audit logging settings
audit:
  enabled: true
  log_file: 'audit.log'
  max_size_mb: 10
